// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGp2INHh0GLUHvSBv0maVkrY5kwlpMoEw',
    appId: '1:658441029085:web:7e61a9f782f0a58f036234',
    messagingSenderId: '658441029085',
    projectId: 'bloc-firebase-gallery',
    authDomain: 'bloc-firebase-gallery.firebaseapp.com',
    storageBucket: 'bloc-firebase-gallery.appspot.com',
    measurementId: 'G-JKC39H4WYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAp9xtP3OpXuNXrcs5YfMFO6F2WhjvWLM',
    appId: '1:658441029085:android:480b7f216dd14666036234',
    messagingSenderId: '658441029085',
    projectId: 'bloc-firebase-gallery',
    storageBucket: 'bloc-firebase-gallery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoqlfF4Fy60mcVBp_V_uHBas5-ex2FoZU',
    appId: '1:658441029085:ios:0876acd698c60eb7036234',
    messagingSenderId: '658441029085',
    projectId: 'bloc-firebase-gallery',
    storageBucket: 'bloc-firebase-gallery.appspot.com',
    iosClientId: '658441029085-udbbgm1tqluuceeqkhl6t9mo10vneejp.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocFirebaseGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoqlfF4Fy60mcVBp_V_uHBas5-ex2FoZU',
    appId: '1:658441029085:ios:0876acd698c60eb7036234',
    messagingSenderId: '658441029085',
    projectId: 'bloc-firebase-gallery',
    storageBucket: 'bloc-firebase-gallery.appspot.com',
    iosClientId: '658441029085-udbbgm1tqluuceeqkhl6t9mo10vneejp.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocFirebaseGallery',
  );
}
